# Generated by Django 4.2.6 on 2023-10-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='logo')),
                ('salary', models.FloatField()),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('web', models.CharField(max_length=120)),
                ('email', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='job')),
                ('logo', models.ImageField(upload_to='logo')),
                ('salary', models.FloatField()),
                ('type', models.CharField(choices=[('full', 'full'), ('part', 'part'), ('remote', 'remote'), ('freelance', 'freelance')], max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_jop', to='jobs.company')),
            ],
        ),
    ]
