# Generated by Django 4.2.6 on 2023-10-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_categorie_rate_remove_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='count',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='job',
        ),
        migrations.RemoveField(
            model_name='company',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='logo',
        ),
        migrations.AddField(
            model_name='job',
            name='categorie',
            field=models.ForeignKey(blank=True, max_length=5000, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_job', to='jobs.categorie', verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_jop', to='jobs.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Experience'),
        ),
    ]
