# Generated by Django 4.2.6 on 2023-10-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_categorie_count_remove_categorie_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_job', to='jobs.categorie', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('1-2 Years', '1-2 Years'), ('2-3 Years', '2-3 Years'), ('3-6 Years', '3-6 Years'), ('6-more', '6-more')], max_length=50, verbose_name='Experience'),
        ),
    ]
