# Generated by Django 4.2.6 on 2023-10-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_categorie_alter_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('1-2 Years', '1-2 Years'), ('2-3 Years', '2-3 Years'), ('3-6 Years', '3-6 Years'), ('6-more', '6-more')], max_length=100, verbose_name='Experience'),
        ),
    ]
